# Generated by Django 5.2 on 2025-04-28 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_accountingservice_serviceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('draft', 'Yangi'), ('in_progress', 'Jarayonda'), ('in_review', 'Ko‘rib chiqilmoqda'), ('approved', 'Tayyor'), ('rejected', 'Bekor qilingan')], default='draft', max_length=20),
        ),
    ]
